package ru.stqa.training.selenium;

import org.junit.Test;
import ru.stqa.*;

public class MenuTest extends TestBase {

  private MenuAdmin menuAdmin;
  private LoginTest loginTest;
  private TemplatePage templatePage;
  private LogotypePage logotypePage;
  private CatalogCsvImportPages catalogCsvImportPages;
  private CatalogPage catalogPage;
  private CountriesPages countriesPages;
  private CsvImportPages csvImportPages;
  private CurrenciesPages currenciesPages;
  private CustomerModulesPages customerModulesPages;
  private CustomersPages customersPages;
  private CustomersCsvImportPages customersCsvImportPages;
  private DeliveryStatusesPages deliveryStatusesPages;
  private GeoZonesPages geoZonesPages;
  private JobModulesPages jobModulesPages;
  private LanguagesPages languagesPages;
  private ManufacturersPages manufacturersPages;
  private MonthlyPages monthlyPages;
  private MostShoppingCustomersPages mostShoppingCustomersPages;
  private MostSoldProductsPages mostSoldProductsPages;
  private NewsletterPages newsletterPages;
  private OptionGroupsPages optionGroupsPages;
  private OrdersPages ordersPages;
  private OrderStatusesPages orderStatusesPages;
  private OrderSuccessModulesPages orderSuccessModulesPages;
  private OrderTotalModulesPages orderTotalModulesPages;
  private OrderActionModulesPages orderActionModulesPages;
  private PagesPages pagesPages;
  private PaymentModulesPages paymentModulesPages;
  private ProductGroupsPages productGroupsPages;
  private QuantityUnitsPages quantityUnitsPages;
  private ScanFilesPages scanFilesPages;
  private SearchTranslationsPages searchTranslationsPages;
  private SettingsPages settingsPages;
  private ShippingModulesPages shippingModulesPages;
  private SlidesPages slidesPages;
  private SoldOutStatusesPages soldOutStatusesPages;
  private StorageEncodingPages storageEncodingPages;
  private SuppliersPages suppliersPages;
  private TaxClassesPages taxClassesPages;
  private TaxRatesPages taxRatesPages;
  private UsersPages usersPages;
  private VQmodsPages vQmodsPages;


  @Test
  public void menuAdminTest() {
    loginTest = new LoginTest();
    menuAdmin = new MenuAdmin(driver);
    templatePage = new TemplatePage(driver);
    logotypePage = new LogotypePage(driver);
    catalogCsvImportPages = new CatalogCsvImportPages(driver);
    customerModulesPages = new CustomerModulesPages(driver);
    countriesPages = new CountriesPages(driver);
    currenciesPages = new CurrenciesPages(driver);
    catalogPage = new CatalogPage(driver);
    manufacturersPages = new ManufacturersPages(driver);
    customersCsvImportPages = new CustomersCsvImportPages(driver);
    deliveryStatusesPages = new DeliveryStatusesPages(driver);
    languagesPages = new LanguagesPages(driver);
    customersPages = new CustomersPages(driver);
    jobModulesPages = new JobModulesPages(driver);
    geoZonesPages = new GeoZonesPages(driver);
    vQmodsPages = new VQmodsPages(driver);
    usersPages = new UsersPages(driver);
    taxRatesPages = new TaxRatesPages(driver);
    taxClassesPages = new TaxClassesPages(driver);
    suppliersPages = new SuppliersPages(driver);
    storageEncodingPages = new StorageEncodingPages(driver);
    soldOutStatusesPages = new SoldOutStatusesPages(driver);
    slidesPages = new SlidesPages(driver);
    shippingModulesPages = new ShippingModulesPages(driver);
    settingsPages = new SettingsPages(driver);
    searchTranslationsPages = new SearchTranslationsPages(driver);
    scanFilesPages = new ScanFilesPages(driver);
    quantityUnitsPages = new QuantityUnitsPages(driver);
    productGroupsPages = new ProductGroupsPages(driver);
    paymentModulesPages = new PaymentModulesPages(driver);
    pagesPages = new PagesPages(driver);
    orderTotalModulesPages = new OrderTotalModulesPages(driver);
    orderSuccessModulesPages = new OrderSuccessModulesPages(driver);
    orderSuccessModulesPages = new OrderSuccessModulesPages(driver);
    orderStatusesPages = new OrderStatusesPages(driver);
    orderActionModulesPages = new OrderActionModulesPages(driver);
    ordersPages = new OrdersPages(driver);
    optionGroupsPages = new OptionGroupsPages(driver);
    newsletterPages = new NewsletterPages(driver);
    mostSoldProductsPages = new MostSoldProductsPages(driver);
    mostShoppingCustomersPages = new MostShoppingCustomersPages(driver);
    monthlyPages = new MonthlyPages(driver);
    csvImportPages = new CsvImportPages(driver);


    loginTest.loginPageObjectTest();
    menuAdmin.clickAppearanceSection();
    templatePage.clickTemplateSection();
    templatePage.isElementPresent();
    logotypePage.clickLogotypeSection();
    menuAdmin.clickCatalogSection();
    catalogPage.clickCatalogSection();
    catalogPage.isElementPresent();
    productGroupsPages.clickProductGroupsSection();
    productGroupsPages.isElementPresent();
    optionGroupsPages.clickOptionGroupsSection();
    optionGroupsPages.isElementPresent();
    manufacturersPages.clickManufacturersSection();
    manufacturersPages.isElementPresent();
    suppliersPages.clickSuppliersSection();
    suppliersPages.isElementPresent();
    deliveryStatusesPages.clickDeliveryStatusesSection();
    deliveryStatusesPages.isElementPresent();
    soldOutStatusesPages.clickSoldOutStatusesSection();
    soldOutStatusesPages.isElementPresent();
    quantityUnitsPages.clickTQuantityUnitsSection();
    quantityUnitsPages.isElementPresent();
    catalogCsvImportPages.clickCatalogCsvImportSection();
    catalogCsvImportPages.isElementPresent();
    menuAdmin.clickCountriesSection();
    countriesPages.isElementPresent();
    menuAdmin.clickCurrenciesSection();
    currenciesPages.isElementPresent();
    menuAdmin.clickCustomersSection();
    customersPages.clickCustomersSection();
    customersPages.isElementPresent();
    customersCsvImportPages.clickCustomersCsvImportSection();
    customersCsvImportPages.isElementPresent();
    newsletterPages.clickNewsletterSection();
    newsletterPages.isElementPresent();
    menuAdmin.clickGeoZonesSection();
    geoZonesPages.isElementPresent();
    menuAdmin.clickLanguagesSection();
    languagesPages.clickLanguagesSection();
    languagesPages.isElementPresent();
    storageEncodingPages.clickStorageEncodingSection();
    storageEncodingPages.isElementPresent();
    menuAdmin.clickModulesSection();
    jobModulesPages.clickJobModulesSection();
    jobModulesPages.isElementPresent();
    customerModulesPages.clickCustomerModulesSection();
    customerModulesPages.isElementPresent();
    shippingModulesPages.clickShippingSection();
    shippingModulesPages.isElementPresent();
    paymentModulesPages.clickPaymentModulesSection();
    paymentModulesPages.isElementPresent();
    orderTotalModulesPages.clickOrderTotalSection();
    orderTotalModulesPages.isElementPresent();
    orderSuccessModulesPages.clickOrderSuccessSection();
    orderSuccessModulesPages.isElementPresent();
    orderActionModulesPages.clickOrderActionSection();
    orderActionModulesPages.isElementPresent();
    menuAdmin.clickOrdersSection();
    ordersPages.clickTOrdersSection();
    ordersPages.isElementPresent();
    orderStatusesPages.clickOrderStatusesSection();
    orderStatusesPages.isElementPresent();
    menuAdmin.clickPagesSection();
    pagesPages.isElementPresent();
    menuAdmin.clickReportsSection();
    monthlyPages.clickMonthlySection();
    monthlyPages.isElementPresent();
    mostSoldProductsPages.clickMostSoldProductsSection();
    mostSoldProductsPages.isElementPresent();
    mostShoppingCustomersPages.clickMostShoppingCustomersSection();
    mostSoldProductsPages.isElementPresent();
    menuAdmin.clickSettingsSection();
    settingsPages.isElementPresent();
    settingsPages.clickSettingsSection();
    settingsPages.clickDefaultsSection();
    settingsPages.clickTitleSettingsPage();
    settingsPages.clickGeneralSection();
    settingsPages.clickListingsSection();
    settingsPages.clickImagesSection();
    settingsPages.clickCheckoutSection();
    settingsPages.clickAdvancedSection();
    settingsPages.clickSecuritySection();
    menuAdmin.clickSlidesSection();
    slidesPages.isElementPresent();
    menuAdmin.clickTaxSection();
    taxClassesPages.clickTaxClassesSection();
    taxClassesPages.isElementPresent();
    taxRatesPages.clickTaxRatesSection();
    taxRatesPages.isElementPresent();
    menuAdmin.clickTranslationsSection();
    searchTranslationsPages.clickSearchTranslations();
    searchTranslationsPages.isElementPresent();
    scanFilesPages.clickScanFilesSection();
    scanFilesPages.isElementPresent();
    csvImportPages.clickCSVImportSection();
    csvImportPages.isElementPresent();
    menuAdmin.clickUsersSection();
    usersPages.isElementPresent();
    menuAdmin.clickVQmodsSection();
    vQmodsPages.clickVQmodsPage();
    vQmodsPages.isElementPresent();
  }
}
